### PR TITLE
side drawer close button

### PR DESCRIPTION
**Pull request by hyetigran**
##  Screenshots (If appropriate)
redirect

image

### CODE REVIEW

**Comment by hyetigran** [comment]
Thank you for bringing this up. This issue was fixed in the previous PR.

**Comment by Hoxtygen** [comment]
Please resolve the conflicting files.

**Comment by hyetigran** [comment]
Resolved

**Comment by Kellswork** [comment]
When I click on dashboard, both the dashboard and my workout are highlighted. It will be nice if the logout link could the same colour as the rest of the link, it really doesn't need a different colour

**Comment by hyetigran** [comment]
logout link is now the same color

**Comment by hyetigran** [comment]
removed 'dashboard' from side drawer on mobile view

**Pull request merged**
