### PR TITLE
Save workout

### PR DESCRIPTION
**Pull request by BenjaminGrabow**
##  What does this PR do
This Pull Request is for saving a workout and fixing bugs in the Workout session

##  Description of task to be completed

- create my workouts component

- create save workout action

- handle redux state change

- save redux state in localstorage

- add new dependency for stop watch and implement it in workout session
 
##  What are the relevant Trello board stories
https://trello.com/c/HhYyiUIe/131-user-should-be-able-to-start-a-workout-when-they-click-the-start-workout-button-on-the-workouts-route-when-we-click-start-it-wil

##  How should this manually be tested

- start local server

- go to the react app

- terminal: git checkout save_workout

- npm install

- npm start

### CODE REVIEW

**Comment by BenjaminGrabow** [comment]
[User should be able to start a workout when they click the start workout button on the workouts route, when we click start it will save it the my collection of 'My workouts'](https://trello.com/c/HhYyiUIe/131-user-should-be-able-to-start-a-workout-when-they-click-the-start-workout-button-on-the-workouts-route-when-we-click-start-it-wil)

**Comment by Hoxtygen** [comment]
I'm having this error. Do take a look and fix

Screenshot 2019-09-05 at 12 18 03 PM

**Comment by shaunmcarmody** [comment]
[As a user I want to add a workout to my collection of 'My workouts' when I click the add button on the workouts route](https://trello.com/c/QO9g7dwV/132-as-a-user-i-want-to-add-a-workout-to-my-collection-of-my-workouts-when-i-click-the-add-button-on-the-workouts-route)

**Comment by shaunmcarmody** [comment]
[As a user I want to add a workout to my collection of 'My workouts' when I click the add button on the workouts route](https://trello.com/c/QO9g7dwV/132-as-a-user-i-want-to-add-a-workout-to-my-collection-of-my-workouts-when-i-click-the-add-button-on-the-workouts-route)

**Comment by BenjaminGrabow** [comment]
> I'm having this error. Do take a look and fix
> 
> Screenshot 2019-09-05 at 12 18 03 PM

You must in the workout-tracker directory install the new dependency with yarn in the terminal. I added a new dependency for the timer and deleted the old one

**Comment by Hoxtygen** [comment]
> > I'm having this error. Do take a look and fix
> > Screenshot 2019-09-05 at 12 18 03 PM
> 
> You must in the workout-tracker directory install the new dependency with yarn in the terminal. I added a new dependency for the timer and deleted the old one

In the PR format which states `Description of task to be completed`, mention the exact name of the dependency you installed and make it known we must run `npm install` to get updated `package.json` file

**Comment by Hoxtygen** [comment]
I like it that you changed the timer from what it was the last time we spoke... Looking good now...

**Pull request merged**
